doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'
        types:
            string_array: App\Doctrine\Types\StringArrayType

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '15'
    orm:
        auto_generate_proxy_classes: true
        enable_lazy_ghost_objects: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        dql:
            string_functions:
                ARRAY_TEXT: App\Doctrine\Functions\ArrayText
                JSONB_EXISTS_ANY: App\Doctrine\Functions\JsonbExistsAny
                JSONB_EXTRACT_PATH_TEXT: App\Doctrine\Functions\JsonbExtractPathText
                JSONB_OBJECT_FIELD: App\Doctrine\Functions\JsonbObjectField
                TO_REAL: App\Doctrine\Functions\ToReal
        mappings:
            Catalog:
                is_bundle: false
                dir: '%kernel.project_dir%/src/Catalog/Entity'
                prefix: 'App\Catalog\Entity'
            Security:
                is_bundle: false
                dir: '%kernel.project_dir%/src/Security/Entity'
                prefix: 'App\Security\Entity'


when@test:
    doctrine:
        dbal:
            # "TEST_TOKEN" is typically set by ParaTest
            dbname_suffix: '_test%env(default::TEST_TOKEN)%'

when@prod:
    doctrine:
        orm:
            auto_generate_proxy_classes: false
            proxy_dir: '%kernel.build_dir%/doctrine/orm/Proxies'
            query_cache_driver:
                type: pool
                pool: doctrine.system_cache_pool
            result_cache_driver:
                type: pool
                pool: doctrine.result_cache_pool

    framework:
        cache:
            pools:
                doctrine.result_cache_pool:
                    adapter: cache.app
                doctrine.system_cache_pool:
                    adapter: cache.system
