doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'
        types:
            string_array: App\Doctrine\Types\StringArrayType

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '13'
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        dql:
            string_functions:
                ARRAY_TEXT: App\Doctrine\Functions\ArrayText
                JSONB_EXISTS_ANY: App\Doctrine\Functions\JsonbExistsAny
                JSONB_EXTRACT_PATH_TEXT: App\Doctrine\Functions\JsonbExtractPathText
                JSONB_OBJECT_FIELD: App\Doctrine\Functions\JsonbObjectField
        mappings:
            App:
                is_bundle: false
                #type: attribute
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App

when@test:
    doctrine:
        dbal:
            # "TEST_TOKEN" is typically set by ParaTest
            dbname_suffix: '_test%env(default::TEST_TOKEN)%'

when@prod:
    doctrine:
        orm:
            auto_generate_proxy_classes: false
            query_cache_driver:
                type: pool
                pool: doctrine.system_cache_pool
            result_cache_driver:
                type: pool
                pool: doctrine.result_cache_pool

    framework:
        cache:
            pools:
                doctrine.result_cache_pool:
                    adapter: cache.app
                doctrine.system_cache_pool:
                    adapter: cache.system
