doctrine:
    dbal:
        default_connection: default
        connections:
            default:
                profiling: '%kernel.debug%'
                url: '%env(resolve:DATABASE_URL)%'

                # IMPORTANT: You MUST configure your server version,
                # either here or in the DATABASE_URL env var (see .env file)
                #server_version: '15'

                mapping_types:
                    enum_status: string

            manticore:
                profiling: '%kernel.debug%'
                url: '%env(resolve:DATABASE_MESSENGER)%'
                driver: pdo_mysql

        types:
            enum_status: App\Core\Doctrine\Types\EnumStatus
    orm:
        #auto_generate_proxy_classes: true
        #enable_lazy_ghost_objects: true
        #report_fields_where_declared: true
        #validate_xml_mapping: true
        #auto_mapping: true
        default_entity_manager: default
        entity_managers:
            default:
                connection: default
                naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
                mappings:
                    AppEntity:
                        is_bundle: false
                        dir: '%kernel.project_dir%/src/Core/Entity'
                        prefix: 'App\Core\Entity'
                dql:
                    numeric_functions:
                        TS_MATCH_VQ: App\Core\Doctrine\Fn\TsMatchVqFn

when@test:
    doctrine:
        dbal:
            # "TEST_TOKEN" is typically set by ParaTest
            dbname_suffix: '_test%env(default::TEST_TOKEN)%'

when@prod:
    doctrine:
        orm:
            auto_generate_proxy_classes: false
            proxy_dir: '%kernel.build_dir%/doctrine/orm/Proxies'
            query_cache_driver:
                type: pool
                pool: doctrine.system_cache_pool
            result_cache_driver:
                type: pool
                pool: doctrine.result_cache_pool

    framework:
        cache:
            pools:
                doctrine.result_cache_pool:
                    adapter: cache.app
                doctrine.system_cache_pool:
                    adapter: cache.system
