# https://symfonycasts.com/screencast/messenger/logger-channel
monolog:
  channels: [obj]
  handlers:
    obj:
      type: service
      id: App\Logger\Monolog\DiffLogDoctrineHandler
      level: debug
      channels: [ "obj" ]
