monolog:
    channels:
        - deprecation # Deprecations are logged in the dedicated "deprecation" channel when it exists

    handlers:
        main:
            type: fingers_crossed
            action_level: debug
            handler: nested
            #excluded_http_codes: [ 404, 405 ]
            channels: [ "!deprecation", "!event", "!doctrine", "!console", "!security" ]#, "!request", "!messenger" ]
            buffer_size: 50 # How many messages should be saved? Prevent memory leaks
        nested:
            type: stream
            path: php://stderr # @see https://gitlab.sblogistica.ru/sberlogistic/php/platform-integration/unified-logger
            level: debug
            formatter: monolog.formatter.json

when@test:
    monolog:
        handlers:
            nested:
                type: stream
                path: "%kernel.logs_dir%/%kernel.environment%.log"
