services:
  php:
    image: srgiz/blog-unit-php:latest
    restart: unless-stopped
    build:
      context: ./docker/php
    environment:
      PS1: "\\u:\\w$$ "
      PHP_INI_SCAN_DIR: "/usr/local/etc/php/conf.d_ext:/usr/local/etc/php/conf.d"
    volumes:
      - ./docker/php/conf.d:/usr/local/etc/php/conf.d_ext
      - ./:/var/www
    depends_on:
      - database-master
      - database-slave1
      - redis
      #- manticore
      - mailer

  postgres:
    image: bitnami/postgresql:17.4.0-debian-12-r11
    restart: unless-stopped
    environment:
      POSTGRESQL_PASSWORD: root
      POSTGRESQL_REPLICATION_USER: repl_user
      POSTGRESQL_REPLICATION_PASSWORD: repl_password
      #POSTGRESQL_LOG_HOSTNAME: true
      #POSTGRESQL_PGAUDIT_LOG: READ,WRITE
