#version: '3.8'

services:
  php:
    container_name: blog-php
    restart: unless-stopped
    image: serginhold/blog-unit--php:latest
    build:
      context: ./docker/php
    environment:
      PS1: "\\u:\\w$$ "
      PHP_INI_SCAN_DIR: "/usr/local/etc/php/conf.d_ext:/usr/local/etc/php/conf.d"
      PHP_IDE_CONFIG: "serverName=127.0.0.7"
    volumes:
      - ./docker/php/conf.d:/usr/local/etc/php/conf.d_ext
      - ./:/var/www
    depends_on:
      - database
      - redis
      #- manticore
      - mailer

  kafka:
    container_name: blog-kafka
    image: 'bitnami/kafka:3.9.0-debian-12-r5'
    #ports:
    #  - '9092:9092'
    environment:
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
    volumes:
      - blog-kafka:/bitnami

  kafka-ui:
    container_name: blog-kafka-ui
    image: provectuslabs/kafka-ui:v0.7.2
    environment:
      KAFKA_CLUSTERS_0_BOOTSTRAP_SERVERS: 'kafka:9092'
      KAFKA_CLUSTERS_0_NAME: local
      #KAFKA_CLUSTERS_0_PROPERTIES_SECURITY_PROTOCOL: SASL_PLAINTEXT
      #KAFKA_CLUSTERS_0_PROPERTIES_SASL_MECHANISM: PLAIN
      #KAFKA_CLUSTERS_0_PROPERTIES_SASL_JAAS_CONFIG: 'org.apache.kafka.common.security.plain.PlainLoginModule required username="admin" password="admin-secret";'
      FILTERING_GROOVY_ENABLED: true # поиск сообщений через: value.type == "test"
    depends_on:
      - kafka

  redis:
    container_name: blog-redis
    restart: unless-stopped
    image: redis:7.4.0-alpine3.20
    volumes:
      - blog-redis:/data

  redisinsight:
    container_name: blog-redisinsight
    image: redis/redisinsight:2.64.1
    volumes:
      - 'blog-redisinsight:/data'
    depends_on:
      - redis

  #manticore:
  #  container_name: blog-manticore
  #  image: manticoresearch/manticore:6.2.12
  #  environment:
  #    - EXTRA=1
  #  restart: unless-stopped
  #  ports:
  #    - "${DOCKER_APP_IP}:9306:9306"
  #    - "${DOCKER_APP_IP}:9308:9308"
  #  ulimits:
  #    nproc: 65535
  #    nofile:
  #      soft: 65535
  #      hard: 65535
  #    memlock:
  #      soft: -1
  #      hard: -1
  #  volumes:
  #    - blog-manticore:/var/lib/manticore

###> doctrine/doctrine-bundle ###
  database:
    container_name: blog-database
    restart: unless-stopped
    image: postgres:16.4-alpine3.20
    environment:
      POSTGRES_PASSWORD: root
    volumes:
      - blog-database:/var/lib/postgresql/data
###< doctrine/doctrine-bundle ###

###> symfony/mailer ###
  mailer:
    container_name: blog-mailer
    restart: unless-stopped
    image: schickling/mailcatcher
###< symfony/mailer ###

networks:
  default:
    name: blog.local

volumes:
  blog-database:
    name: blog-database
  blog-redis:
    name: blog-redis
  blog-redisinsight:
    name: blog-redisinsight
  blog-kafka:
    name: blog-kafka
  blog-manticore:
    name: blog-manticore
