version: '3.8'

services:
  nginx:
    container_name: blog-nginx
    image: nginx:1.21.4-alpine
    ports:
      - ${DOCKER_APP_IP}:80:80
    volumes:
      - ./docker/nginx/conf.d/blog.conf:/etc/nginx/conf.d/blog.conf
      - ./:/var/www
    depends_on:
      - php

  php:
    container_name: blog-php
    image: serginhold/blog-php:latest
    build:
      context: ./docker/php
    environment:
      PS1: "\\u:\\w$$ "
      PHP_INI_SCAN_DIR: "/usr/local/etc/php/conf.d_ext:/usr/local/etc/php/conf.d"
    volumes:
      - ./docker/php/conf.d:/usr/local/etc/php/conf.d_ext
      - ./:/var/www
    depends_on:
      - postgres

  postgres:
    # https://www.postgresql.org/ftp/pgadmin/pgadmin4/v5.6/
    container_name: blog-pg
    image: postgres:14.1-alpine3.15
    restart: always
    ports:
      - ${DOCKER_APP_IP}:5432:5432
    environment:
      POSTGRES_PASSWORD: root
    volumes:
      - blog-pg:/var/lib/postgresql/data

networks:
  default:
    name: blog.local

volumes:
  blog-pg:
    name: blog-pg
