version: '3.8'

services:
  nginx:
    container_name: blog-nginx
    image: serginhold/blog-nginx:latest
    build:
      context: ./docker/nginx
    ports:
      - ${APP_IP}:${APP_PORT}:80
    volumes:
      - ./docker/nginx/blog.conf:/etc/nginx/conf.d/blog.conf
      - ./:/var/www
    depends_on:
      - php
  php:
    container_name: blog-php
    image: serginhold/blog-php:latest
    build:
      context: ./docker/php
    environment:
      PHP_INI_SCAN_DIR: "/usr/local/etc/php/conf.d_ext:/usr/local/etc/php/conf.d"
    volumes:
      - ./docker/php:/usr/local/etc/php/conf.d_ext
      - ./:/var/www
    depends_on:
      - mysql
  mysql:
    container_name: blog-db
    image: mysql:8.0.25
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - ${APP_IP}:3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - blog-db:/var/lib/mysql
    #restart: always

networks:
  default:
    name: blog.local

volumes:
  blog-db:
    name: blog-db
