version: '3.8'

services:
  nginx:
    container_name: blog-nginx
    restart: unless-stopped
    image: nginx:1.23.0-alpine
    ports:
      - ${DOCKER_APP_IP}:80:80
    volumes:
      - ./docker/nginx/conf.d/blog.conf:/etc/nginx/conf.d/blog.conf
      - ./:/var/www
    depends_on:
      - php

  php:
    container_name: blog-php
    restart: unless-stopped
    image: serginhold/blog-php:latest
    build:
      context: ./docker/php
    environment:
      PS1: "\\u:\\w$$ "
      PHP_INI_SCAN_DIR: "/usr/local/etc/php/conf.d_ext:/usr/local/etc/php/conf.d"
    volumes:
      - ./docker/php/conf.d:/usr/local/etc/php/conf.d_ext
      - ./:/var/www
    depends_on:
      - database
      - redis
      - mailer

  redis:
    container_name: blog-redis
    restart: unless-stopped
    image: redis:7.0.2-alpine3.16
    ports:
      - ${DOCKER_APP_IP}:6379:6379

###> doctrine/doctrine-bundle ###
  database:
    container_name: blog-database
    restart: unless-stopped
    image: postgres:14.4-alpine3.16
    ports:
      - ${DOCKER_APP_IP}:5432:5432
    environment:
      POSTGRES_PASSWORD: root
    volumes:
      - blog-database:/var/lib/postgresql/data
###< doctrine/doctrine-bundle ###

###> symfony/mailer ###
  mailer:
    container_name: blog-mailer
    restart: unless-stopped
    image: schickling/mailcatcher
    ports:
      - ${DOCKER_APP_IP}:1025:1025
      - ${DOCKER_APP_IP}:1080:1080
###< symfony/mailer ###

networks:
  default:
    name: blog.local

volumes:
  blog-database:
    name: blog-database
