controllers:
    # todo: снести
    type: attribute
    resource:
        path: ../src/Controller/
        namespace: App\Controller

app_catalog:
    type: attribute
    resource: '../src/Catalog/Controller/'

app_security:
    type: attribute
    resource: '../src/Security/Controller/'
