services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    SerginhoLD\JsonRpcBundle\:
        resource: '../src/'
        exclude:
            - '../src/Exception/'
            - '../src/Request/'
            - '../src/Response/'
            - '../src/JsonRpcBundle.php'

    #SerginhoLD\JsonRpcBundle\Handler\RequestHandlerInterface:
    #    class: SerginhoLD\JsonRpcBundle\Handler\RequestHandler
    #    public: true
