services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    SerginhoLD\JsonRpcBundle\:
        resource: '../src/'
        exclude:
            - '../src/Exception/'
            - '../src/Request/'
            - '../src/Response/'
            - '../src/Serializer/'
            - '../src/JsonRpcBundle.php'
