name: "@nav"
description: ""
namespace: "App\\Nav\\"

# "Public API" of the modulite: classes, functions, constants, etc.
# Symbols not listed here will be internal.
export:
#  - "@messi/channels"
#  - "@messi/folders"

# Class members to exclude, they override "export".
force-internal:

# Dependencies: other modulites, global classes, defines, etc.
require:
  - "@core"
  - "#symfony/routing"
  - "#symfony/cache-contracts"

# Granting partial access to internal symbols, "as an exception".
allow-internal-access:
